[package]
name = "cppvtbl-macros"
version = "0.1.0"
edition = "2021"
description = "Helper macros for cppvtbl"
license = "MIT"

[dependencies]
quote = "1.0"
syn = {version = "1.0", features = ["full"]}
proc-macro2 = "1.0"

[lib]
proc-macro = true
